default_language_version:
    python: python3.11
default_install_hook_types: [pre-commit, pre-push, pre-rebase]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: name-tests-test
        args: ['--pytest-test-first']
    -   id: no-commit-to-branch
        args: [--branch, main]
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.47.0
    hooks:
    -   id: markdownlint
        args: ['--config', 'pyproject.toml', '--fix']
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.15.16
  hooks:
    - id: ruff-check
    - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
    -   id: mypy
        additional_dependencies: ['types-pytz', 'types-requests']
-   repo: https://github.com/mrtazz/checkmake.git
    rev: 0.2.2
    hooks:
    -   id: checkmake
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: v2.11.0
  hooks:
    - id: pyproject-fmt
      args: ['--check']
- repo: local
  hooks:
  - id: commit-msg
    name: Check commit message
    language: pygrep
    entry: '^(feature|fix|docs|refactor)!?: [a-zA-Z0-9-_ ]+[a-zA-Z0-9-_ ]+.*'
    args:
    - --negate
    stages:
    - commit-msg
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: make test
    language: system
    pass_filenames: false
    always_run: true
    stages:
    - pre-push
