[project]
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.0",
  "Programming Language :: Python :: 3.1",
  "Programming Language :: Python :: 3.2",
  "Programming Language :: Python :: 3.3",
  "Programming Language :: Python :: 3.4",
  "Programming Language :: Python :: 3.5",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
dependencies = [
  "httpx",
  "jinja2",
]
description = "Create a Coverage report comment on Github PR"
license = {file = "LICENSE"}
maintainers = [
  {name = "Pradeep Tammali", email = "pradeeptammaliwork@gmail.com"},
]
name = "python-coverage-comment"
readme = "README.md"
requires-python = ">=3.0"
version = "2.1"

[project.urls]
Homepage = "https://github.com/PradeepTammali/python-coverage-comment"
Issues = "https://github.com/PradeepTammali/python-coverage-comment/issues"
[build-system]
build-backend = "setuptools.build_meta"
requires = [
  "setuptools",
]

[project.scripts]
codecov = "codecov.main:main"
[tool.autopep8]
in-place = false
max_line_length = 120

[tool.black]
line-length = 120
skip-string-normalization = true

[tool.ruff]
ignore = [
  # format
  'E501', # line too long
]
line-length = 120
select = [
  'E', # Errors
  'W', # Warnings
  'F', # Formatting
  'S', # Bandit
]
target-version = 'py311'

[tool.ruff.mccabe]
max-complexity = 10

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
quote-style = 'single'

[tool.ruff.per-file-ignores]
# Ignore assert usage in tests
'tests/*.py' = ['S101']

[tool.isort]
combine_as_imports = true
line_length = 120
profile = "black"

[tool.flake8]
ignore = ['E501', 'W503', 'W504']

[tool.pytest.ini_options]
env = ['APP_ENVIRONMENT = unittest']

[tool.coverage.report]
show_missing = true

[[tool.mypy.overrides]]
check_untyped_defs = true
ignore_missing_imports = true
implicit_optional = true
module = 'codecov.*'

[tool.pylint.MASTER]
ignore-paths = ['tests/*']

[tool.pylint.FORMAT]
indent-string = '    '
max-line-length = 120

[tool.pylint."MESSAGES CONTROL"]
disable = '''
    missing-docstring,
    line-too-long,
    import-error,
    fixme,
    no-value-for-parameter,
    too-few-public-methods
'''

[tool.bandit]
exclude_dirs = ["tests/*"]
